[2025-01-11T08:47:46.118+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: insert_data.ft_balance_f scheduled__2025-01-06T00:00:00+00:00 [queued]>
[2025-01-11T08:47:46.130+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: insert_data.ft_balance_f scheduled__2025-01-06T00:00:00+00:00 [queued]>
[2025-01-11T08:47:46.131+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 3
[2025-01-11T08:47:46.314+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): ft_balance_f> on 2025-01-06 00:00:00+00:00
[2025-01-11T08:47:46.322+0000] {standard_task_runner.py:60} INFO - Started process 242 to run task
[2025-01-11T08:47:46.325+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'insert_data', 'ft_balance_f', 'scheduled__2025-01-06T00:00:00+00:00', '--job-id', '567', '--raw', '--subdir', 'DAGS_FOLDER/insert_data.py', '--cfg-path', '/tmp/tmp_4ilorkp']
[2025-01-11T08:47:46.327+0000] {standard_task_runner.py:88} INFO - Job 567: Subtask ft_balance_f
[2025-01-11T08:47:46.374+0000] {task_command.py:423} INFO - Running <TaskInstance: insert_data.ft_balance_f scheduled__2025-01-06T00:00:00+00:00 [running]> on host 403e7aadd7ee
[2025-01-11T08:47:46.496+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='agushchin' AIRFLOW_CTX_DAG_ID='insert_data' AIRFLOW_CTX_TASK_ID='ft_balance_f' AIRFLOW_CTX_EXECUTION_DATE='2025-01-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-06T00:00:00+00:00'
[2025-01-11T08:47:46.512+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-11T08:47:46.578+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-01-11T08:47:46.589+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=insert_data, task_id=ft_balance_f, execution_date=20250106T000000, start_date=20250111T084746, end_date=20250111T084746
[2025-01-11T08:47:46.619+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-01-11T08:47:46.642+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
