[2024-12-30T17:42:10.285+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: insert_data.call_clear_all_data scheduled__2024-12-29T00:00:00+00:00 [queued]>
[2024-12-30T17:42:10.300+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: insert_data.call_clear_all_data scheduled__2024-12-29T00:00:00+00:00 [queued]>
[2024-12-30T17:42:10.301+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2024-12-30T17:42:10.341+0000] {taskinstance.py:2191} INFO - Executing <Task(SQLExecuteQueryOperator): call_clear_all_data> on 2024-12-29 00:00:00+00:00
[2024-12-30T17:42:10.353+0000] {standard_task_runner.py:60} INFO - Started process 305 to run task
[2024-12-30T17:42:10.360+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'insert_data', 'call_clear_all_data', 'scheduled__2024-12-29T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/insert_data.py', '--cfg-path', '/tmp/tmpr8_2u3uj']
[2024-12-30T17:42:10.370+0000] {standard_task_runner.py:88} INFO - Job 10: Subtask call_clear_all_data
[2024-12-30T17:42:10.515+0000] {task_command.py:423} INFO - Running <TaskInstance: insert_data.call_clear_all_data scheduled__2024-12-29T00:00:00+00:00 [running]> on host 403e7aadd7ee
[2024-12-30T17:42:10.651+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='agushchin' AIRFLOW_CTX_DAG_ID='insert_data' AIRFLOW_CTX_TASK_ID='call_clear_all_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-29T00:00:00+00:00'
[2024-12-30T17:42:10.653+0000] {sql.py:276} INFO - Executing: CALL dm.clear_all_data()
[2024-12-30T17:42:10.668+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2024-12-30T17:42:10.684+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2024-12-30T17:42:10.686+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 391, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 158, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (::1), port 5433 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5433 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2024-12-30T17:42:10.702+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=insert_data, task_id=call_clear_all_data, execution_date=20241229T000000, start_date=20241230T174210, end_date=20241230T174210
[2024-12-30T17:42:10.729+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 10 for task call_clear_all_data (connection to server at "localhost" (::1), port 5433 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5433 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
; 305)
[2024-12-30T17:42:10.759+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-12-30T17:42:10.832+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
