[2025-01-04T08:09:49.023+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: insert_data.ft_balance_f scheduled__2025-01-03T00:00:00+00:00 [queued]>
[2025-01-04T08:09:49.039+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: insert_data.ft_balance_f scheduled__2025-01-03T00:00:00+00:00 [queued]>
[2025-01-04T08:09:49.041+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-01-04T08:09:49.520+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): ft_balance_f> on 2025-01-03 00:00:00+00:00
[2025-01-04T08:09:49.535+0000] {standard_task_runner.py:60} INFO - Started process 100 to run task
[2025-01-04T08:09:49.543+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'insert_data', 'ft_balance_f', 'scheduled__2025-01-03T00:00:00+00:00', '--job-id', '309', '--raw', '--subdir', 'DAGS_FOLDER/insert_data.py', '--cfg-path', '/tmp/tmpiavctr18']
[2025-01-04T08:09:49.547+0000] {standard_task_runner.py:88} INFO - Job 309: Subtask ft_balance_f
[2025-01-04T08:09:49.631+0000] {task_command.py:423} INFO - Running <TaskInstance: insert_data.ft_balance_f scheduled__2025-01-03T00:00:00+00:00 [running]> on host 403e7aadd7ee
[2025-01-04T08:09:49.753+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='agushchin' AIRFLOW_CTX_DAG_ID='insert_data' AIRFLOW_CTX_TASK_ID='ft_balance_f' AIRFLOW_CTX_EXECUTION_DATE='2025-01-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-03T00:00:00+00:00'
[2025-01-04T08:09:49.782+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-04T08:09:49.854+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-01-04T08:09:49.872+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=insert_data, task_id=ft_balance_f, execution_date=20250103T000000, start_date=20250104T080949, end_date=20250104T080949
[2025-01-04T08:09:49.916+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-01-04T08:09:49.989+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
